/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moria;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinnie
 */
public class enterInfoGui extends javax.swing.JFrame {

    /**
     * Creates new form enterInfoGui
     */
    public enterInfoGui() {
        initComponents();
    }
    public String user;
    public String professor;
    public String course;
    public String days ="";
    public String group;
    public String time;
    public Connection con;
    
    public void acceptUser(String uid, Connection c)
    {
        this.user = uid;
        this.con = c;
    }
    public void acceptGroup(String g)
    {
        this.group = g;
    }
    public boolean validInput()
    {
        boolean valid = true;
        
        if(this.professorField.getText().equals("") ||this.courseField.getText().equals("") 
                || this.startTimeField.getText().equals("") || this.endTimeField.getText().equals(""))
        {
            valid = false;
        }
        if( !(this.mondayButton.isSelected() || this.thursdayButton.isSelected() || this.tuesdayButton.isSelected()
                || this.wednesdayButton.isSelected() || this.fridayButton.isSelected()))
        {
            valid = false;
        }
        
        
        return valid;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        professorField = new javax.swing.JTextField();
        mondayButton = new javax.swing.JCheckBox();
        tuesdayButton = new javax.swing.JCheckBox();
        wednesdayButton = new javax.swing.JCheckBox();
        thursdayButton = new javax.swing.JCheckBox();
        fridayButton = new javax.swing.JCheckBox();
        startTimeField = new javax.swing.JTextField();
        endTimeField = new javax.swing.JTextField();
        courseField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        professorField.setBorder(null);
        professorField.setOpaque(false);
        getContentPane().add(professorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 20));

        mondayButton.setOpaque(false);
        getContentPane().add(mondayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 282, 20, 20));

        tuesdayButton.setToolTipText("");
        tuesdayButton.setOpaque(false);
        getContentPane().add(tuesdayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 282, 20, 20));

        wednesdayButton.setBackground(null);
        wednesdayButton.setBorder(null);
        wednesdayButton.setOpaque(false);
        getContentPane().add(wednesdayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 282, 20, 20));

        thursdayButton.setOpaque(false);
        getContentPane().add(thursdayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 282, 20, 20));

        fridayButton.setOpaque(false);
        getContentPane().add(fridayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 282, 20, 20));

        startTimeField.setBorder(null);
        startTimeField.setOpaque(false);
        getContentPane().add(startTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 50, 20));

        endTimeField.setBorder(null);
        endTimeField.setOpaque(false);
        getContentPane().add(endTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 50, 20));

        courseField.setBorder(null);
        courseField.setOpaque(false);
        getContentPane().add(courseField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, 20));

        confirmButton.setBorder(null);
        confirmButton.setBorderPainted(false);
        confirmButton.setContentAreaFilled(false);
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, 60));

        doneButton.setBorder(null);
        doneButton.setContentAreaFilled(false);
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 0, 50, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enterInfoImage.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        this.professor = this.professorField.getText();
        this.course = this.courseField.getText();
        this.time = this.startTimeField.getText() + " - " + this.endTimeField.getText();
        
        // get day string
        if(this.mondayButton.isSelected())
        {
            this.days += "M";
        }
        if(this.tuesdayButton.isSelected())
        {
            this.days += "T";
        }
        if(this.wednesdayButton.isSelected())
        {
            this.days += "W";
        }
        if(this.thursdayButton.isSelected())
        {
            this.days += "TH";
        }
        if(this.fridayButton.isSelected())
        {
            this.days += "F";
        }
        
        //add to database here
        if(validInput())
        {
            try{
                String sql = "INSERT INTO [dbo].[Classes]([Professor],[Course ID],[Meeting Days],[Meeting Time],[UserID],[Group]) VALUES(?,?,?,?,?,?)";
                PreparedStatement ps = this.con.prepareStatement(sql);
                ps.setString(1,this.professor);
                ps.setString(2,this.course);
                ps.setString(3,this.days);
                ps.setString(4,this.time);
                ps.setString(5,this.user);
                ps.setString(6 ,this.group);
                ps.executeUpdate();

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
            this.professor = "";
            this.course = "";
            this.time = "";
            this.days = "";
            this.professorField.setText("");
            this.courseField.setText("");
            this.startTimeField.setText("");
            this.endTimeField.setText("");
            this.mondayButton.setSelected(false);
            this.tuesdayButton.setSelected(false);
            this.wednesdayButton.setSelected(false);
            this.thursdayButton.setSelected(false);
            this.fridayButton.setSelected(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid input, Please Ensure all fields are full, and at least one day is checked!");
        }
        
        
      
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enterInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enterInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enterInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enterInfoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enterInfoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField courseField;
    private javax.swing.JButton doneButton;
    private javax.swing.JTextField endTimeField;
    private javax.swing.JCheckBox fridayButton;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox mondayButton;
    private javax.swing.JTextField professorField;
    private javax.swing.JTextField startTimeField;
    private javax.swing.JCheckBox thursdayButton;
    private javax.swing.JCheckBox tuesdayButton;
    private javax.swing.JCheckBox wednesdayButton;
    // End of variables declaration//GEN-END:variables
}
