package moria;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vinnie
 */
public class loginGui extends javax.swing.JFrame {

    /**
     * Creates new form loginGui
     */
    public loginGui() {
        initComponents();

    }
    
    public Connection con;
    
    public void acceptConnection(Connection c)
    {
        this.con = c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        userNameField = new javax.swing.JTextField();
        Password1Field = new javax.swing.JPasswordField();
        Password2Field = new javax.swing.JPasswordField();
        password2Label = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        newAccountButton = new javax.swing.JButton();
        godModeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameField.setBackground(null);
        userNameField.setBorder(null);
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 190, 20));

        Password1Field.setBackground(null);
        Password1Field.setBorder(null);
        getContentPane().add(Password1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 190, 20));
        getContentPane().add(Password2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 127, -1));

        password2Label.setText("Re-type Password");
        password2Label.setFocusable(false);
        getContentPane().add(password2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 104, -1));

        okButton.setBorderPainted(false);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 30, -1));

        quitButton.setBorderPainted(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 40, -1));

        newAccountButton.setBorder(null);
        newAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAccountButtonActionPerformed(evt);
            }
        });
        getContentPane().add(newAccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 180, 30));

        godModeButton.setText("God Mode");
        godModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godModeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(godModeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginGui.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 390));

        getAccessibleContext().setAccessibleName("Moria Login Page");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String userNameLogin = new String(this.userNameField.getText());
        String passwordOne = new String(this.Password1Field.getPassword());
        String passwordTwo = new String(this.Password2Field.getPassword());
        
        if(userNameLogin.equals(""))
        {
           JOptionPane.showMessageDialog(this, "User name can not be left empty!");
        }
        else if(! passwordOne.equals(passwordTwo))
        {
            JOptionPane.showMessageDialog(this, "Passwords Must Match!");
        }
        else if(passwordOne.equals("") || passwordTwo.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Passwords can not be left blank");
        }
        else
        {
            try{
            String sql = "Select * from [dbo].[Login] where [Username]=? and [Password] =?";
            String getGroup = "Select [Group] from [dbo].[Login] where [Username]=?";
            PreparedStatement ps = this.con.prepareStatement(sql);
            PreparedStatement groupPS = this.con.prepareStatement(getGroup);
            groupPS.setString(1, userNameLogin);
            
            ps.setString(1, userNameLogin);
            ps.setString(2, passwordOne);     
            ResultSet result = ps.executeQuery();
            ResultSet resultG = groupPS.executeQuery();            
            if(result.next())
            {
                if (resultG.next())
                {
                    String groupID = resultG.getString(1);
                    mainGui main = new mainGui();           
                    main.acceptGroup(groupID);
                    main.acceptUser(userNameLogin, this.con); 
                    main.setVisible(true);
                    this.setVisible(false);
                    System.out.println("Login Successful");
                }
            }
            else
            {
               JOptionPane.showMessageDialog(this, "Login Failed!"); 
               this.userNameField.setText("");
               this.Password1Field.setText("");
               this.Password2Field.setText("");
            }

            }
            catch (Exception e)
            {
                System.out.println(e);
            }
       
            
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void newAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAccountButtonActionPerformed
        newAccountGui newAcc = new newAccountGui();
        newAcc.acceptConnection(this.con);
        newAcc.setVisible(false);
    }//GEN-LAST:event_newAccountButtonActionPerformed

    private void godModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godModeButtonActionPerformed
        mainGui main = new mainGui();
        main.setVisible(true);
    }//GEN-LAST:event_godModeButtonActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password1Field;
    private javax.swing.JPasswordField Password2Field;
    private javax.swing.JButton godModeButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton newAccountButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel password2Label;
    private javax.swing.JButton quitButton;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
